# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Scott Watermasysk
favicon: assets/favicon.ico
email: scottwater@gmail.com
description: Family, Life, Business, Code, and some sports
baseurl: "" # The subpath of your site, e.g. /blog
url: https://scottw.com # The base hostname & protocol for your site
twitter: https://twitter.com/scottw
github: https://github.com/scottwater

feed_items: 10

markdown: kramdown

# PAGINATION
# paginate: 5
# paginate_path: "p:num"
pagination:
  enabled: true
permalink: "/:title"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-purgecss
  - jekyll-paginate-v2

include:
  - _pages
  - _redirects

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - netlify.toml
  - bin
  - .gitignore

# Pages path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename
