# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       Scott Watermasysk
favicon:     assets/favicon.ico
email:       scottwater@gmail.com
description: Family, Life, Business, Code, and some sports
baseurl:     '' # The subpath of your site, e.g. /blog
url:         https://scottw.com # The base hostname & protocol for your site
twitter:     https://twitter.com/scottw
github:      https://github.com/scottwater
instagram:   https://instagram.com/skotwatir

markdown:  kramdown

# PAGINATION
paginate: 5
paginate_path: "p:num"
permalink: "/:title"

sass:
  sass_dir: _sass
  #style: compressed

plugins:
  - jekyll-paginate
  - jekyll-json-feed

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename
